//
//  AppString.swift
//  BidCast
//
//  Created by JAM_E_329 on 14/05/25.
//


import Foundation

struct AppString{
    static let acitivity = "Activity".localized
    static let email = "Email Address".localized
    static let password = "Password".localized
    static let enterEmail = "Enter Email Address".localized
    static let enterPassword = "Enter Password".localized
    static let rememberMe = "Remember Me".localized
    static let forgotPassword = "Forgot Password?".localized
    static let login = "Login".localized
    static let newUser = "New User?".localized
    static let createAccount = "Create Account".localized
    static let privacyPolicy = "Privacy Policy"
    static let termOfService = "Terms of service"
    static let pleaseEnterEmail = "Please enter email address".localized
    static let pleaseEnterPassword = "Please enter Password".localized
    static let confirmPassword = "Confirm Password".localized
    static let confirmNewPassword = "Confirm New Password".localized
    static let pleaseEnterNewPassword = "Please enter New Password".localized
    static let pleaseConfirmPassword = "Please Confirm Password".localized
    static let passwordNotLessThan =  "Password can not be less than 8 characters".localized
    static let passwordNotMatched =  "Password and Confirm Password can not be different".localized
    static let continueBtn = "Continue".localized
    static let chooseLanguage = "Choose Language".localized
    static let loginFailed = "Login Failed".localized
    static let failedToLogin = "Fail to login with current credentials".localized
    static let retryLogin =  "Retry Login".localized
    static let error =  "Error".localized
    static let emailAddressNotAssociated = "Please enter the email address associated with your account".localized
    static let submit =  "Submit".localized
    static let pleaseEnterValidEmailAddress = "Please enter a valid mail address".localized
    static let ok = "Ok".localized
    static let enterCode = "Enter Code".localized
    static let enterOtp = "Enter OTP".localized
    static let resendOtp = "Resend OTP".localized
    static let otpNotEmpty = "OTP can not be empty".localized
    static let pleaseEnterOtp  = "Please enter the OTP".localized
    static let otpNumeric = "OTP must be numeric".localized
    static let verifyOtp = "Verify OTP".localized
    static let resetPassword = "Reset Password".localized
    static let proceedToLogin = "Proceed to Login".localized
    static let createYourAccount = "Create Your Account".localized
    static let firstName = "First Name".localized
    static let enterFirstName = "Enter First Name".localized
    static let lastName = "Last Name".localized
    static let enterLastName = "Enter Last Name".localized
    static let pleaseEnterFirstName = "Please enter First Name".localized
    static let pleaseEnterLastName = "Please enter Last Name".localized
    static let backToLogin  = "Back to Login".localized
    static let selectALanguage  = "Select a language".localized
    static let fullName = "First Name".localized
    static let subject = "Subject".localized
    static let enterSubject = "Enter Subject".localized
    static let message = "Message".localized
    static let sendMessage = "Send Message".localized
    static let getInTouch = "Get In Touch".localized
    static let enterFullName = "Enter Full Name".localized
    static let weAreHereToHelp = "We're here to help! Send us your queries and we'll get back to you soon.".localized
    static let enterYourMessage = "Enter Your Message Here".localized
    static let enterconfirmPassword = "Enter Confirm Password".localized
    static let forgetPassword = "Forgot Password".localized
    static let enterCodeSent = "Enter the code sent to your email address.".localized
    static let newShow =  "New Show".localized
    static let successOtpMessage = "Success! Please enter the code that was sent to the email associated with your account.".localized
    static let successNewPassword = "Success! Please enter your new password below.".localized
    static let addOverallRating = "Please add overall rating".localized
    static let addshippingRating = "Please add shipping rating".localized
    static let addpackagingRating = "Please add packaging rating".localized
    static let addaccuracyRating = "Please add accuracy rating".localized
    static let adddescriptionRating = "Please add description rating".localized
    static let addComment = "Please add comment".localized
    static let Account = "Account".localized
    static let SellerHub = "Seller Hub".localized
    static let MyAccount = "My Account".localized
    static let CompleteProfile = "Complete Profile".localized
    static let CompleteYourProfile = "Complete Your Profile".localized
    static let Username = "Username".localized
    static let EnterUserName = "Enter User Name".localized
    static let Bio = "Bio".localized
    static let TellUsAboutYourself = "Tell us about yourself".localized
    static let Update = "Update".localized
    static let PleaseUploadYourProfileImage = "Please upload your profile image".localized
    static let  PleaseEnterYourFirstName = "Please enter your first name".localized
    static let PleaseEnterYourLastName = "Please enter your last name".localized
    static let PleaseEnteraUsername = "Please enter a username".localized
    static let PleaseEnteraBio = "Please enter a bio".localized
    static let SelectMediaSource = "Select Media Source".localized
    static let Camera = "Camera".localized
    static let PhotoLibrary = "Photo Library".localized
    static let Cancel = "Cancel".localized
    static let UploadPhoto = "Upload Photo".localized
    static let Inventory = "Inventory".localized
    static let NoInventoryFound = "No inventory found".localized
    static let whatAreYouLookingFor = "What are you looking for?".localized
    static let MyOrders = "My Orders".localized
    static let Wallet = "Wallet".localized
    static let NoTransactionHistoryFound = "No Transaction history found".localized
    static let AvailableBalance = "Available Balance".localized
    static let EarlyPayout = "Early Payout".localized
    static let avaialbelForPayOut = "Available for\nPayout".localized
    static let Processing = "Processing".localized
    static let  YouAreEligibleForEarlyPayout  = "You're eligible for early payout".localized
    static let PayoutHistory = "Payout History".localized
    static let NoPayoutHistoryFound = "No Payout history found".localized
    static let Offers = "Offers".localized
    static let Decline = "Decline".localized
    static let Accept = "Accept".localized
    static let Accepted = "Accepted".localized
    static let Rejected = "Rejected".localized
    static let Tips = "Tips".localized
    static let Shipping = "Shipping".localized
    static let AffiliateProgram = "Affiliate Program".localized
    static let Earn$100PerReferral = "Earn $100 Per Referral".localized
    static let InviteSellersandEarnRewards = "Invite sellers and earn rewards when they succeed".localized
    static let ShareYourLink = "Share Your Link".localized
    static let InviteSellers = "Invite sellers using your unique code".localized
    static let ShareInviteLink = "Share Invite Link"
    static let CodeCopied = "Code copied!"
    static let CopyCode = "Copy Code"
    static let  Earn$100Reward = "Earn $100 Reward"
    static let  WhenYourReferral = "When your referral makes their first sale"
    static let YourReferralStatus = "Your Referral Stats"
    static let  TotalReferrals  = "Total Referrals"
    static let Earnings = "Earnings"
}
