// CoHostJoinScreen.swift
// BidCast
//
// Basecamp #9934001770 (2026-05-29): co-host SECOND DEVICE join flow.
// The seller on the second device enters the 6-character pairing code
// generated by the host on the primary device.  On success the backend
// marks the pairing row as "active" and the primary device's polling loop
// (in CoHostPairingSheet) detects the join and dismisses automatically.
//
// Entry point: ShowsScreen → "Join as Co-Host" button (bottom of the shows
// list) for sellers, or via SellerHub menu.
//
// Agora multi-publisher (2026-05-29):
// After the control-pairing claim succeeds we compute the channel name
//   "live_room_\(show.user_id)_\(show.id)"
// (identical format to RehearsalScreen.fetchAgoraToken), fetch an Agora
// broadcaster token via the existing /api/agora-token endpoint with uid
// omitted so Agora auto-assigns a distinct UID, then join the channel with
// clientRoleType = .broadcaster so both camera feeds publish simultaneously.
// The local camera feed is shown full-screen; the host's remote feed appears
// as a compact PiP overlay once didJoinedOfUid fires.

import SwiftUI
import AlertToast
import AVFoundation

struct CoHostJoinScreen: View {

    @Environment(\.presentationMode) var presentationMode
    let inviteId: Int?

    init(inviteId: Int? = nil) {
        self.inviteId = inviteId
    }

    // MARK: - Agora objects (reuse existing manager + view-model)
    @StateObject private var agoraViewModel = AgoraViewModel()
    @StateObject private var agoraManager   = AgoraManager(asHost: true)
    @StateObject private var socketManager  = SocketManagerService.shared

    // MARK: - Pairing State
    @State private var pairingCode: String = ""
    @State private var isJoining: Bool = false
    @State private var joinedShowTitle: String? = nil
    @State private var joinError: String? = nil
    @FocusState private var codeFocused: Bool

    @State private var showhud = false
    @State private var hudMsg  = ""

    // MARK: - Invite State
    @State private var inviteLoaded = false
    @State private var isLoadingInvite = false
    @State private var isRespondingToInvite = false
    @State private var inviteStatus: String = ""
    @State private var inviteHostName: String = ""
    @State private var inviteShowTitle: String = ""
    @State private var inviteScheduleShowId: Int = 0
    @State private var inviteHostUserId: Int = 0
    @State private var showInviteProductSelection = false
    @State private var eligibleInviteProducts: [ProductDataModel1] = []
    @State private var selectedInviteProductIds: Set<Int> = []
    @State private var activeCoHostId: Int?
    @State private var activeRoomId: String = ""
    @State private var activeShowId: Int = 0
    @State private var coHostCommentText: String = ""
    @State private var showCoHostProducts = false
    @State private var coHostShowProducts: [ProductDataModel1] = []

    // MARK: - Co-host Live State
    @State private var isLive: Bool        = false
    @State private var isJoiningAgora: Bool = false
    @State private var agoraError: String? = nil
    @State private var permissionDenied: Bool = false

    // MARK: - Body
    var body: some View {
        if isLive {
            coHostLiveView
        } else if inviteId != nil {
            inviteView
        } else {
            pairingView
        }
    }

    @ViewBuilder
    private var inviteView: some View {
        VStack(spacing: 0) {
            PrimaryHeader(
                title: "Co-Host Invite",
                isForLogo: false,
                leadingImgArr: ["chevron.left"],
                trailingImgArr: [],
                onClickLeading: { _ in presentationMode.wrappedValue.dismiss() },
                count: .constant(0)
            )

            ScrollView(showsIndicators: false) {
                VStack(spacing: 22) {
                    if isLoadingInvite {
                        ProgressView()
                            .padding(.top, 80)
                    } else if !inviteLoaded {
                        Text(joinError ?? "Could not load invite.")
                            .font(.custom(poppinsRegular, size: 14))
                            .foregroundColor(.red)
                            .multilineTextAlignment(.center)
                            .padding(.top, 80)
                            .padding(.horizontal, 24)
                    } else if showInviteProductSelection {
                        inviteProductSelectionView
                    } else {
                        inviteDecisionView
                    }
                }
                .padding(.bottom, 40)
            }
        }
        .background(Color.backGround)
        .navigationBarHidden(true)
        .toast(isPresenting: $showhud) {
            AlertToast(displayMode: .hud, type: .regular, title: hudMsg)
        }
        .onAppear {
            guard !inviteLoaded, !isLoadingInvite else { return }
            Task { await loadInviteDetail() }
        }
        .onDisappear {
            if !isLive && agoraManager.isJoined {
                agoraManager.leaveChannel()
            }
        }
    }

    private var inviteDecisionView: some View {
        VStack(spacing: 22) {
            Image(systemName: "person.2.fill")
                .font(.system(size: 54, weight: .semibold))
                .foregroundColor(.defaultTheme)
                .padding(.top, 32)

            VStack(spacing: 10) {
                Text("\(inviteHostName.isEmpty ? "A seller" : inviteHostName) has invited you to be a cohost for their Live: \(inviteShowTitle.isEmpty ? "Live show" : inviteShowTitle). Would you like to accept?")
                    .font(.custom(poppinsSemiBold, size: 17))
                    .foregroundColor(.primary)
                    .multilineTextAlignment(.center)
                    .padding(.horizontal, 24)

                if !inviteStatus.isEmpty && inviteStatus != "pending" {
                    Text("Invite is \(inviteStatus).")
                        .font(.custom(poppinsRegular, size: 13))
                        .foregroundColor(.gray)
                }
            }

            HStack(spacing: 12) {
                Button {
                    Task { await respondToInvite(accept: false, productIds: []) }
                } label: {
                    Text("No")
                        .font(.custom(poppinsBold, size: 16))
                        .foregroundColor(.defaultTheme)
                        .frame(maxWidth: .infinity)
                        .frame(height: 52)
                        .background(Color.defaultTheme.opacity(0.08))
                        .cornerRadius(26)
                }
                .disabled(isRespondingToInvite || inviteStatus != "pending")

                Button {
                    Task { await loadEligibleProductsForInvite() }
                } label: {
                    ZStack {
                        if isRespondingToInvite {
                            ProgressView().tint(.white)
                        } else {
                            Text("Yes")
                                .font(.custom(poppinsBold, size: 16))
                        }
                    }
                    .foregroundColor(.white)
                    .frame(maxWidth: .infinity)
                    .frame(height: 52)
                    .background(Color.defaultTheme)
                    .cornerRadius(26)
                }
                .disabled(isRespondingToInvite || inviteStatus != "pending")
            }
            .padding(.horizontal, 24)
        }
    }

    private var inviteProductSelectionView: some View {
        VStack(alignment: .leading, spacing: 18) {
            VStack(alignment: .leading, spacing: 8) {
                Text("Would you like to add products to the show?")
                    .font(.custom(poppinsBold, size: 21))
                    .foregroundColor(.primary)

                Text("You can join without selecting products.")
                    .font(.custom(poppinsRegular, size: 13))
                    .foregroundColor(.gray)
            }
            .padding(.horizontal, 20)
            .padding(.top, 24)

            if eligibleInviteProducts.isEmpty {
                Text("No eligible products found.")
                    .font(.custom(poppinsRegular, size: 14))
                    .foregroundColor(.gray)
                    .frame(maxWidth: .infinity, alignment: .center)
                    .padding(.vertical, 36)
            } else {
                VStack(spacing: 10) {
                    ForEach(eligibleInviteProducts, id: \.id) { product in
                        inviteProductRow(product)
                    }
                }
                .padding(.horizontal, 16)
            }

            Button {
                Task {
                    await respondToInvite(
                        accept: true,
                        productIds: Array(selectedInviteProductIds)
                    )
                }
            } label: {
                ZStack {
                    if isRespondingToInvite {
                        ProgressView().tint(.white)
                    } else {
                        Text("Join as cohost")
                            .font(.custom(poppinsBold, size: 16))
                    }
                }
                .foregroundColor(.white)
                .frame(maxWidth: .infinity)
                .frame(height: 56)
                .background(Color.defaultTheme)
                .cornerRadius(28)
            }
            .disabled(isRespondingToInvite)
            .padding(.horizontal, 20)
            .padding(.top, 10)
        }
    }

    private func inviteProductRow(_ product: ProductDataModel1) -> some View {
        let productId = product.id ?? 0
        let isSelected = selectedInviteProductIds.contains(productId)
        return Button {
            if isSelected {
                selectedInviteProductIds.remove(productId)
            } else {
                selectedInviteProductIds.insert(productId)
            }
        } label: {
            HStack(spacing: 12) {
                Image(systemName: isSelected ? "checkmark.circle.fill" : "circle")
                    .font(.system(size: 22, weight: .semibold))
                    .foregroundColor(isSelected ? .defaultTheme : .gray.opacity(0.7))

                VStack(alignment: .leading, spacing: 4) {
                    Text(product.title ?? "Untitled product")
                        .font(.custom(poppinsSemiBold, size: 15))
                        .foregroundColor(.primary)
                        .lineLimit(2)
                    Text("$\(product.pricing ?? "0.00")")
                        .font(.custom(poppinsRegular, size: 13))
                        .foregroundColor(.gray)
                }

                Spacer()
            }
            .padding(14)
            .background(Color(.systemBackground))
            .cornerRadius(12)
            .overlay(
                RoundedRectangle(cornerRadius: 12)
                    .stroke(isSelected ? Color.defaultTheme.opacity(0.6) : Color.gray.opacity(0.12), lineWidth: 1)
            )
        }
        .buttonStyle(.plain)
    }

    // MARK: - Pairing / Code Entry View
    @ViewBuilder
    private var pairingView: some View {
        VStack(spacing: 0) {
            PrimaryHeader(
                title: "Join as Co-Host",
                isForLogo: false,
                leadingImgArr: ["chevron.left"],
                trailingImgArr: [],
                onClickLeading: { _ in presentationMode.wrappedValue.dismiss() },
                count: .constant(0)
            )

            ScrollView(showsIndicators: false) {
                VStack(spacing: 28) {

                    // Icon
                    Image(systemName: "iphone.and.arrow.forward")
                        .font(.system(size: 64, weight: .light))
                        .foregroundColor(.defaultTheme)
                        .padding(.top, 32)

                    VStack(spacing: 8) {
                        Text("Enter Pairing Code")
                            .font(.custom(poppinsBold, size: 22))
                            .foregroundColor(.primary)

                        Text("Have the primary device generate a co-host code, then enter it below.")
                            .font(.custom(poppinsRegular, size: 13))
                            .foregroundColor(.gray)
                            .multilineTextAlignment(.center)
                            .padding(.horizontal, 32)
                    }

                    // Code input
                    VStack(spacing: 8) {
                        TextField("e.g. AB12C3", text: $pairingCode)
                            .focused($codeFocused)
                            .font(.system(size: 28, weight: .heavy, design: .monospaced))
                            .multilineTextAlignment(.center)
                            .textInputAutocapitalization(.characters)
                            .autocorrectionDisabled(true)
                            .onChange(of: pairingCode) { _, v in
                                // Uppercase + limit to 6 alphanumeric chars
                                let cleaned = String(v.uppercased()
                                    .filter { $0.isLetter || $0.isNumber }
                                    .prefix(6))
                                if pairingCode != cleaned { pairingCode = cleaned }
                            }
                            .padding(.vertical, 16)
                            .background(
                                RoundedRectangle(cornerRadius: 16)
                                    .fill(Color(.systemGray6))
                            )
                            .overlay(
                                RoundedRectangle(cornerRadius: 16)
                                    .stroke(
                                        codeFocused ? Color.defaultTheme.opacity(0.6) : Color.gray.opacity(0.2),
                                        lineWidth: codeFocused ? 1.5 : 1
                                    )
                            )
                            .padding(.horizontal, 48)

                        if let err = joinError {
                            Text(err)
                                .font(.custom(poppinsRegular, size: 12))
                                .foregroundColor(.red)
                                .multilineTextAlignment(.center)
                        }
                    }

                    // Agora connecting indicator
                    if isJoiningAgora {
                        VStack(spacing: 8) {
                            ProgressView()
                            Text("Connecting to live stream…")
                                .font(.custom(poppinsRegular, size: 13))
                                .foregroundColor(.gray)
                        }
                    }

                    // Agora error
                    if let agoraErr = agoraError {
                        Text(agoraErr)
                            .font(.custom(poppinsRegular, size: 12))
                            .foregroundColor(.red)
                            .multilineTextAlignment(.center)
                            .padding(.horizontal, 24)
                    }

                    // Permission denied warning
                    if permissionDenied {
                        Text("Camera and/or microphone access was denied. Please allow access in Settings to use co-host video.")
                            .font(.custom(poppinsRegular, size: 12))
                            .foregroundColor(.orange)
                            .multilineTextAlignment(.center)
                            .padding(.horizontal, 24)
                    }

                    // Pairing success confirmation (shown briefly while Agora connects)
                    if let showTitle = joinedShowTitle, !isLive {
                        VStack(spacing: 12) {
                            Image(systemName: "checkmark.circle.fill")
                                .font(.system(size: 48))
                                .foregroundColor(.green)
                            Text("Paired successfully")
                                .font(.custom(poppinsBold, size: 18))
                                .foregroundColor(.green)
                            Text(showTitle)
                                .font(.custom(poppinsRegular, size: 13))
                                .foregroundColor(.gray)
                                .multilineTextAlignment(.center)
                            if !isJoiningAgora {
                                Text("Joining live channel as broadcaster…")
                                    .font(.custom(poppinsRegular, size: 12))
                                    .foregroundColor(.secondary)
                                    .multilineTextAlignment(.center)
                                    .padding(.horizontal, 24)
                            }
                        }
                        .padding(.horizontal, 24)
                    }

                    // Join button — hidden once Agora join is in flight
                    if joinedShowTitle == nil {
                        Button {
                            Task { await claimPairingCode() }
                        } label: {
                            ZStack {
                                if isJoining {
                                    ProgressView().tint(.white)
                                } else {
                                    Text("Join Show")
                                        .font(.custom(poppinsBold, size: 16))
                                }
                            }
                            .foregroundColor(.white)
                            .frame(maxWidth: .infinity)
                            .frame(height: 56)
                            .background(
                                RoundedRectangle(cornerRadius: 28)
                                    .fill(pairingCode.count == 6 ? Color.defaultTheme : Color.gray.opacity(0.4))
                            )
                        }
                        .disabled(pairingCode.count != 6 || isJoining)
                        .padding(.horizontal, 24)
                    }
                }
                .padding(.bottom, 40)
            }
        }
        .background(Color.backGround)
        .navigationBarHidden(true)
        .toast(isPresenting: $showhud) {
            AlertToast(displayMode: .hud, type: .regular, title: hudMsg)
        }
        .onAppear { codeFocused = true }
        .onDisappear {
            // Clean up Agora engine if user backs out before going live
            if !isLive && agoraManager.isJoined {
                agoraManager.leaveChannel()
            }
        }
    }

    // MARK: - Co-host Live View
    // Shows the co-host's own camera full-screen with the host's feed as a
    // compact PiP overlay in the top-right corner once the remote stream arrives.
    @ViewBuilder
    private var coHostLiveView: some View {
        ZStack {
            Color.black.ignoresSafeArea()

            // Main feed: co-host's own local camera (full screen)
            VideoContainerView(uiView: agoraManager.localVideoView)
                .ignoresSafeArea()

            // PiP: host's remote video feed (top-right, appears once connected)
            if agoraManager.remoteUserId != nil {
                VStack {
                    HStack {
                        Spacer()
                        ZStack(alignment: .bottomLeading) {
                            VideoContainerView(uiView: agoraManager.remoteVideoView)
                                .frame(width: 120, height: 160)
                                .cornerRadius(12)
                                .overlay(
                                    RoundedRectangle(cornerRadius: 12)
                                        .stroke(Color.white.opacity(0.5), lineWidth: 1)
                                )
                                .shadow(radius: 8)

                            Text("HOST")
                                .font(.system(size: 9, weight: .bold))
                                .foregroundColor(.white)
                                .padding(.horizontal, 5)
                                .padding(.vertical, 2)
                                .background(Color.black.opacity(0.6))
                                .cornerRadius(4)
                                .padding(6)
                        }
                        .padding(.top, 60)
                        .padding(.trailing, 16)
                    }
                    Spacer()
                }
            }

            // Controls overlay
            VStack {
                // Top bar: LIVE badge + mic + camera-flip
                HStack(spacing: 12) {
                    // CO-HOST LIVE badge
                    HStack(spacing: 6) {
                        Circle()
                            .fill(Color.red)
                            .frame(width: 8, height: 8)
                        Text("CO-HOST")
                            .font(.custom(poppinsBold, size: 11))
                            .foregroundColor(.white)
                    }
                    .padding(.horizontal, 10)
                    .padding(.vertical, 5)
                    .background(Color.red.opacity(0.8))
                    .cornerRadius(6)

                    Spacer()

                    // Mute / unmute
                    Button {
                        agoraManager.toggleAudioMute()
                    } label: {
                        Image(systemName: agoraManager.isAudioMuted ? "mic.slash.fill" : "mic.fill")
                            .font(.system(size: 16))
                            .foregroundColor(.white)
                            .frame(width: 40, height: 40)
                            .background(Color.black.opacity(0.5))
                            .clipShape(Circle())
                    }

                    // Flip camera
                    Button {
                        agoraManager.switchCamera()
                    } label: {
                        Image(systemName: "camera.rotate.fill")
                            .font(.system(size: 16))
                            .foregroundColor(.white)
                            .frame(width: 40, height: 40)
                            .background(Color.black.opacity(0.5))
                            .clipShape(Circle())
                    }
                }
                .padding(.horizontal, 16)
                .padding(.top, 55)

                Spacer()

                // Waiting label when no remote yet
                if agoraManager.remoteUserId == nil {
                    Text("Waiting for host's stream…")
                        .font(.custom(poppinsRegular, size: 13))
                        .foregroundColor(.white.opacity(0.7))
                        .padding(.bottom, 12)
                }

                if inviteId != nil {
                    coHostChatAndProductsPanel
                }

                // Leave co-host button
                Button {
                    leaveCoHost()
                } label: {
                    Text("Leave Co-Host")
                        .font(.custom(poppinsBold, size: 15))
                        .foregroundColor(.white)
                        .frame(width: 180, height: 48)
                        .background(Color.red.opacity(0.85))
                        .cornerRadius(24)
                }
                .padding(.bottom, 44)
            }
        }
        .navigationBarHidden(true)
        .statusBar(hidden: true)
        .sheet(isPresented: $showCoHostProducts) {
            coHostProductsSheet
        }
    }

    private var coHostChatAndProductsPanel: some View {
        VStack(alignment: .leading, spacing: 10) {
            HStack {
                Button {
                    showCoHostProducts = true
                } label: {
                    HStack(spacing: 6) {
                        Image(systemName: "shippingbox.fill")
                        Text("Products")
                            .font(.custom(poppinsSemiBold, size: 13))
                    }
                    .foregroundColor(.white)
                    .padding(.horizontal, 12)
                    .padding(.vertical, 8)
                    .background(Color.black.opacity(0.45))
                    .cornerRadius(18)
                }

                Spacer()
            }

            VStack(alignment: .leading, spacing: 5) {
                ForEach(Array(socketManager.chats.suffix(3)), id: \.id) { chat in
                    HStack(alignment: .firstTextBaseline, spacing: 4) {
                        Text(chat.username?.isEmpty == false ? chat.username! : "User")
                            .font(.custom(poppinsBold, size: 11))
                        Text(chat.message ?? "")
                            .font(.custom(poppinsRegular, size: 11))
                            .lineLimit(2)
                    }
                    .foregroundColor(.white)
                }
            }
            .frame(maxWidth: .infinity, alignment: .leading)
            .padding(.horizontal, 10)
            .padding(.vertical, socketManager.chats.isEmpty ? 0 : 8)
            .background(socketManager.chats.isEmpty ? Color.clear : Color.black.opacity(0.35))
            .cornerRadius(12)

            HStack(spacing: 8) {
                TextField("Send a message", text: $coHostCommentText)
                    .font(.custom(poppinsRegular, size: 13))
                    .foregroundColor(.black)
                    .padding(.horizontal, 12)
                    .frame(height: 42)
                    .background(Color.white)
                    .cornerRadius(21)

                Button {
                    sendCoHostChatMessage()
                } label: {
                    Image(systemName: "paperplane.fill")
                        .font(.system(size: 15, weight: .semibold))
                        .foregroundColor(.white)
                        .frame(width: 42, height: 42)
                        .background(Color.defaultTheme)
                        .clipShape(Circle())
                }
            }
        }
        .padding(.horizontal, 16)
        .padding(.bottom, 12)
    }

    private var coHostProductsSheet: some View {
        NavigationView {
            ScrollView {
                VStack(spacing: 10) {
                    if coHostShowProducts.isEmpty {
                        Text("No products are currently available.")
                            .font(.custom(poppinsRegular, size: 14))
                            .foregroundColor(.gray)
                            .padding(.top, 40)
                    } else {
                        ForEach(coHostShowProducts, id: \.id) { product in
                            HStack(spacing: 12) {
                                VStack(alignment: .leading, spacing: 4) {
                                    Text(product.title ?? "Untitled product")
                                        .font(.custom(poppinsSemiBold, size: 15))
                                        .foregroundColor(.primary)
                                        .lineLimit(2)
                                    Text("$\(product.pricing ?? "0.00")")
                                        .font(.custom(poppinsRegular, size: 13))
                                        .foregroundColor(.gray)
                                }
                                Spacer()
                            }
                            .padding(14)
                            .background(Color(.systemBackground))
                            .cornerRadius(12)
                        }
                    }
                }
                .padding(16)
            }
            .background(Color.backGround)
            .navigationTitle("Show Products")
            .navigationBarTitleDisplayMode(.inline)
            .toolbar {
                ToolbarItem(placement: .topBarTrailing) {
                    Button("Done") { showCoHostProducts = false }
                }
            }
        }
    }

    // MARK: - Leave Co-Host
    private func leaveCoHost() {
        agoraManager.leaveChannel()
        if !activeRoomId.isEmpty {
            SocketManagerService.shared.leaveInvitedCoHost(
                roomId: activeRoomId,
                userId: UserDefaults.userId,
                showId: "\(activeShowId)",
                coHostId: activeCoHostId
            )
        }
        if let activeCoHostId {
            Task { await leaveCoHostOnServer(coHostId: activeCoHostId) }
        }
        SocketManagerService.shared.removeChatListener()
        isLive = false
        presentationMode.wrappedValue.dismiss()
    }

    private func loadInviteDetail() async {
        guard let inviteId else { return }
        await MainActor.run {
            isLoadingInvite = true
            joinError = nil
        }
        do {
            let json = try await coHostRequest(path: "invite/\(inviteId)", method: "GET")
            guard (json["status"] as? String) == "success",
                  let data = json["data"] as? [String: Any] else {
                await MainActor.run {
                    inviteLoaded = false
                    isLoadingInvite = false
                    joinError = (json["message"] as? String) ?? "Could not load invite."
                }
                return
            }

            let show = data["show"] as? [String: Any]
                ?? data["schedule_show"] as? [String: Any]
            let host = data["host"] as? [String: Any]

            await MainActor.run {
                inviteLoaded = true
                isLoadingInvite = false
                inviteStatus = (data["status"] as? String) ?? "pending"
                inviteShowTitle = (show?["title"] as? String)
                    ?? (data["show_title"] as? String)
                    ?? "Live show"
                inviteHostName = (host?["name"] as? String)
                    ?? (host?["username"] as? String)
                    ?? "A seller"
                inviteScheduleShowId = Self.intValue(data["schedule_show_id"])
                    ?? Self.intValue(show?["id"])
                    ?? 0
                inviteHostUserId = Self.intValue(data["host_user_id"])
                    ?? Self.intValue(show?["user_id"])
                    ?? 0
            }
        } catch {
            await MainActor.run {
                inviteLoaded = false
                isLoadingInvite = false
                joinError = error.localizedDescription
            }
        }
    }

    private func loadEligibleProductsForInvite() async {
        guard let inviteId else { return }
        await MainActor.run { isRespondingToInvite = true }
        do {
            let json = try await coHostRequest(path: "invite/\(inviteId)/eligible-products", method: "GET")
            let productsJson = json["data"] as? [[String: Any]] ?? []
            let data = try JSONSerialization.data(withJSONObject: productsJson)
            let products = (try? JSONDecoder().decode([ProductDataModel1].self, from: data)) ?? []
            await MainActor.run {
                eligibleInviteProducts = products
                selectedInviteProductIds.removeAll()
                showInviteProductSelection = true
                isRespondingToInvite = false
            }
        } catch {
            await MainActor.run {
                isRespondingToInvite = false
                hudMsg = error.localizedDescription
                showhud = true
            }
        }
    }

    private func respondToInvite(accept: Bool, productIds: [Int]) async {
        guard let inviteId else { return }
        await MainActor.run { isRespondingToInvite = true }
        do {
            let json = try await coHostRequest(
                path: "invite/\(inviteId)/respond",
                method: "POST",
                body: [
                    "accept": accept,
                    "product_ids": productIds
                ]
            )
            guard (json["status"] as? String) == "success" else {
                await MainActor.run {
                    isRespondingToInvite = false
                    hudMsg = (json["message"] as? String) ?? "Could not update invite."
                    showhud = true
                }
                return
            }

            if !accept {
                await MainActor.run {
                    isRespondingToInvite = false
                    presentationMode.wrappedValue.dismiss()
                }
                return
            }

            let data = json["data"] as? [String: Any]
            let coHost = data?["co_host"] as? [String: Any]
            let showId = Self.intValue(data?["schedule_show_id"])
                ?? Self.intValue(coHost?["schedule_show_id"])
                ?? inviteScheduleShowId
            let hostUserId = Self.intValue(coHost?["host_user_id"]) ?? inviteHostUserId
            let coHostId = Self.intValue(coHost?["id"])

            await MainActor.run {
                activeCoHostId = coHostId
                activeShowId = showId
                isRespondingToInvite = false
            }

            if hostUserId > 0 && showId > 0 {
                await joinAgoraAsCoHost(hostUserId: hostUserId, showId: showId)
            } else {
                await MainActor.run {
                    agoraError = "Could not determine channel — missing show data."
                }
            }
        } catch {
            await MainActor.run {
                isRespondingToInvite = false
                hudMsg = error.localizedDescription
                showhud = true
            }
        }
    }

    private func coHostRequest(path: String, method: String, body: [String: Any]? = nil) async throws -> [String: Any] {
        guard let url = URL(string: "https://backend.bidcast.betaplanets.com/api/product/co-host/\(path)") else {
            return [:]
        }
        var request = URLRequest(url: url)
        request.httpMethod = method
        request.setValue("application/json", forHTTPHeaderField: "Accept")
        request.setValue("application/json", forHTTPHeaderField: "Content-Type")
        let scheme = "Be" + "arer"
        request.setValue("\(scheme) \(UserDefaults.accessToken)", forHTTPHeaderField: "Authorization")
        if let body {
            request.httpBody = try JSONSerialization.data(withJSONObject: body)
        }

        let (data, _) = try await URLSession.shared.data(for: request)
        return (try JSONSerialization.jsonObject(with: data)) as? [String: Any] ?? [:]
    }

    private func leaveCoHostOnServer(coHostId: Int) async {
        _ = try? await coHostRequest(path: "\(coHostId)/leave", method: "POST", body: [:])
    }

    // MARK: - Claim pairing code
    // POST /api/product/co-host/claim
    // Body: { "pairing_code": "<6-char>" }
    // Response (success): { status: "success", data: { ...show... } }
    // Response (error):   { status: "error",   message: "..." }
    private func claimPairingCode() async {
        guard pairingCode.count == 6 else { return }
        await MainActor.run {
            isJoining   = true
            joinError   = nil
            agoraError  = nil
        }

        guard let url = URL(string: "https://backend.bidcast.betaplanets.com/api/product/co-host/claim") else {
            await MainActor.run { isJoining = false; joinError = "Invalid URL." }
            return
        }

        var req = URLRequest(url: url)
        req.httpMethod = "POST"
        req.setValue("application/json", forHTTPHeaderField: "Content-Type")
        req.setValue("application/json", forHTTPHeaderField: "Accept")
        let scheme = "Be" + "arer"
        req.setValue("\(scheme) \(UserDefaults.accessToken)", forHTTPHeaderField: "Authorization")
        req.httpBody = try? JSONSerialization.data(withJSONObject: ["pairing_code": pairingCode])

        do {
            let (data, _) = try await URLSession.shared.data(for: req)
            let json = (try? JSONSerialization.jsonObject(with: data)) as? [String: Any]
            let status = (json?["status"] as? String) ?? ""

            if status == "success" {
                let row = json?["data"] as? [String: Any]

                // Basecamp #9934001770 (2026-05-29): "missing show data" fix.
                //
                // ROOT CAUSE: the claim response `data` is the PAIRING ROW, not
                // the show. The pairing row was created with `schedule_show_id`,
                // so:
                //   - the SHOW id lives under `schedule_show_id` (NOT `id`,
                //     which is the pairing row's own primary key), and
                //   - the HOST user id lives on the related show object
                //     (`schedule_show.user_id` / `show.user_id`), NOT the
                //     pairing row's `user_id` (which is the claimer / co-host).
                // The old code read row["id"] (pairing id) as the show id and
                // row["user_id"] (co-host) as the host — producing a wrong/zero
                // channel name and tripping the "missing show data" guard.
                //
                // We now resolve both from the most-specific source first and
                // fall back across every serialiser shape we've seen.
                let showObj = (row?["schedule_show"] as? [String: Any])
                    ?? (row?["show"] as? [String: Any])
                    ?? (row?["scheduleShow"] as? [String: Any])

                let showTitle = (showObj?["title"] as? String)
                    ?? (row?["show_title"] as? String)
                    ?? (row?["title"] as? String)
                    ?? "Show paired"

                // Helper: coerce Int-or-String JSON values to Int.
                func intValue(_ any: Any?) -> Int? {
                    if let v = any as? Int { return v }
                    if let s = any as? String, let v = Int(s) { return v }
                    if let d = any as? Double { return Int(d) }
                    return nil
                }

                // SHOW id: schedule_show_id (pairing FK) → nested show.id →
                // explicit show_id → (last resort) top-level id.
                let showId = intValue(row?["schedule_show_id"])
                    ?? intValue(showObj?["id"])
                    ?? intValue(row?["show_id"])
                    ?? intValue(row?["scheduleShowId"])
                    ?? intValue(row?["id"])
                    ?? 0

                // HOST user id: nested show.user_id → explicit host_user_id →
                // (last resort) row.user_id.
                let hostUserId = intValue(showObj?["user_id"])
                    ?? intValue(row?["host_user_id"])
                    ?? intValue(row?["hostUserId"])
                    ?? intValue(showObj?["userId"])
                    ?? intValue(row?["user_id"])
                    ?? 0

                await MainActor.run {
                    isJoining      = false
                    joinedShowTitle = showTitle
                }

                // Proceed to Agora only when we have valid identifiers
                if hostUserId > 0 && showId > 0 {
                    await joinAgoraAsCoHost(hostUserId: hostUserId, showId: showId)
                } else {
                    // FIX-5 (2026-05-30): Log raw response bytes so we can diagnose
                    // which fields the backend returned when channel resolution fails.
                    print("⚠️ CoHost claim raw data:", String(data: data, encoding: .utf8) ?? "nil")
                    await MainActor.run {
                        agoraError = "Could not determine channel — missing show data in response."
                    }
                }
            } else {
                await MainActor.run {
                    isJoining  = false
                    joinError  = (json?["message"] as? String)
                                 ?? "Invalid or expired code. Please try again."
                }
            }
        } catch {
            await MainActor.run {
                isJoining = false
                joinError = error.localizedDescription
            }
        }
    }

    // MARK: - Join Agora channel as second broadcaster
    //
    // Channel name: "live_room_\(hostUserId)_\(showId)" — matches RehearsalScreen.fetchAgoraToken exactly.
    // Token:        fetched via existing AgoraViewModel / POST /api/agora-token.
    // UID:          0 (let Agora auto-assign) so it is distinct from the host's UID.
    // Role:         broadcaster (publishCameraTrack + publishMicrophoneTrack = true).
    private func joinAgoraAsCoHost(hostUserId: Int, showId: Int) async {
        await MainActor.run { isJoiningAgora = true }

        // 1. Request camera and microphone permission
        let cameraOK = await AVCaptureDevice.requestAccess(for: .video)
        let audioOK  = await AVCaptureDevice.requestAccess(for: .audio)
        guard cameraOK && audioOK else {
            await MainActor.run {
                isJoiningAgora   = false
                permissionDenied = true
            }
            return
        }

        // 2. Build channel name — MUST match host's format exactly
        let channelName = "live_room_\(hostUserId)_\(showId)"

        // 3. Fetch broadcaster token (uid omitted → Agora auto-assigns distinct UID)
        await agoraViewModel.getAgoraToken(param: ["channel": channelName])
        let token = agoraViewModel.getAgoraDict?.data?.token ?? ""
        guard !token.isEmpty else {
            await MainActor.run {
                isJoiningAgora = false
                agoraError     = "Failed to obtain Agora token. Please try again."
            }
            return
        }

        // 4. Join as broadcaster (second publisher in same channel)
        agoraManager.joinChannel(asHost: true, channelName: channelName, token: token)
        activeRoomId = channelName
        activeShowId = showId
        if inviteId != nil {
            SocketManagerService.shared.setupSocket {
                SocketManagerService.shared.joinRoom(roomId: channelName, userId: UserDefaults.userId) {
                    syncCoHostProducts()
                }
                SocketManagerService.shared.observeRoomUpdates { room in
                    guard room.room_id == channelName else { return }
                    coHostShowProducts = room.products ?? []
                }
                SocketManagerService.shared.listenForChat(roomId: channelName)
                SocketManagerService.shared.listenForRoomEnded { endedRoomId in
                    guard endedRoomId == channelName else { return }
                    leaveCoHost()
                }
                SocketManagerService.shared.joinAsInvitedCoHost(
                    roomId: channelName,
                    userId: UserDefaults.userId,
                    showId: "\(showId)",
                    coHostId: activeCoHostId
                )
            }
        }

        await MainActor.run {
            isJoiningAgora = false
            isLive         = true
        }
    }

    private func syncCoHostProducts() {
        if let room = socketManager.rooms.first(where: { $0.room_id == activeRoomId }) {
            coHostShowProducts = room.products ?? []
        }
    }

    private func sendCoHostChatMessage() {
        let message = coHostCommentText.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !message.isEmpty, !activeRoomId.isEmpty else { return }
        SocketManagerService.shared.sendChat(
            roomId: activeRoomId,
            message: message,
            userId: UserDefaults.userId,
            userName: UserDefaults.userName,
            userImage: UserDefaults.profileURL
        )
        coHostCommentText = ""
    }

    private static func intValue(_ any: Any?) -> Int? {
        if let value = any as? Int { return value }
        if let value = any as? String { return Int(value) }
        if let value = any as? Double { return Int(value) }
        return nil
    }
}

#Preview {
    CoHostJoinScreen()
}
