// CoHostJoinScreen.swift
// BidCast
//
// Basecamp #9934001770 (2026-05-29): co-host SECOND DEVICE join flow.
// The seller on the second device enters the 6-character pairing code
// generated by the host on the primary device.  On success the backend
// marks the pairing row as "active" and the primary device's polling loop
// (in CoHostPairingSheet) detects the join and dismisses automatically.
//
// Entry point: ShowsScreen → "Join as Co-Host" button (bottom of the shows
// list) for sellers, or via SellerHub menu.
//
// Agora multi-publisher note: this screen handles the CONTROL-PAIRING side
// only (presence + status).  Full Agora multi-publisher video (two camera
// feeds from two devices in the same channel with both as publishers) is
// NOT implemented here — it requires:
//   1. The host to invite the co-host's UID as a co-publisher via
//      Agora's interactive live streaming audience→publisher role switch,
//      OR both devices to join the same RTC channel directly.
//   2. A new Agora token for the co-host device with a publisher role
//      (the backend would need to expose a co-host token endpoint).
//   3. AgoraKit integration in this screen (startPreview, joinChannel,
//      setClientRole(.broadcaster)).
// That work is estimated at ~1–2 days (backend token endpoint + iOS Agora
// integration + UI for the co-host's local camera preview).
// Tracking: Basecamp #9934001770 comment thread.

import SwiftUI
import AlertToast

struct CoHostJoinScreen: View {

    @Environment(\.presentationMode) var presentationMode

    // MARK: - State
    @State private var pairingCode: String = ""
    @State private var isJoining: Bool = false
    @State private var joinedShowTitle: String? = nil
    @State private var joinError: String? = nil
    @FocusState private var codeFocused: Bool

    @State private var showhud = false
    @State private var hudMsg = ""

    // MARK: - Body
    var body: some View {
        VStack(spacing: 0) {
            PrimaryHeader(
                title: "Join as Co-Host",
                isForLogo: false,
                leadingImgArr: ["chevron.left"],
                trailingImgArr: [],
                onClickLeading: { _ in presentationMode.wrappedValue.dismiss() },
                count: .constant(0)
            )

            ScrollView(showsIndicators: false) {
                VStack(spacing: 28) {

                    // Illustration / icon
                    Image(systemName: "iphone.and.arrow.forward")
                        .font(.system(size: 64, weight: .light))
                        .foregroundColor(.defaultTheme)
                        .padding(.top, 32)

                    VStack(spacing: 8) {
                        Text("Enter Pairing Code")
                            .font(.custom(poppinsBold, size: 22))
                            .foregroundColor(.primary)

                        Text("Have the primary device generate a co-host code, then enter it below.")
                            .font(.custom(poppinsRegular, size: 13))
                            .foregroundColor(.gray)
                            .multilineTextAlignment(.center)
                            .padding(.horizontal, 32)
                    }

                    // Code input
                    VStack(spacing: 8) {
                        TextField("e.g. AB12C3", text: $pairingCode)
                            .focused($codeFocused)
                            .font(.system(size: 28, weight: .heavy, design: .monospaced))
                            .multilineTextAlignment(.center)
                            .textInputAutocapitalization(.characters)
                            .autocorrectionDisabled(true)
                            .onChange(of: pairingCode) { _, v in
                                // Uppercase + limit to 6 chars
                                let cleaned = String(v.uppercased().filter { $0.isLetter || $0.isNumber }.prefix(6))
                                if pairingCode != cleaned { pairingCode = cleaned }
                            }
                            .padding(.vertical, 16)
                            .background(
                                RoundedRectangle(cornerRadius: 16)
                                    .fill(Color(.systemGray6))
                            )
                            .overlay(
                                RoundedRectangle(cornerRadius: 16)
                                    .stroke(codeFocused ? Color.defaultTheme.opacity(0.6) : Color.gray.opacity(0.2),
                                            lineWidth: codeFocused ? 1.5 : 1)
                            )
                            .padding(.horizontal, 48)

                        if let err = joinError {
                            Text(err)
                                .font(.custom(poppinsRegular, size: 12))
                                .foregroundColor(.red)
                                .multilineTextAlignment(.center)
                        }
                    }

                    if let showTitle = joinedShowTitle {
                        // Joined confirmation
                        VStack(spacing: 12) {
                            Image(systemName: "checkmark.circle.fill")
                                .font(.system(size: 48))
                                .foregroundColor(.green)
                            Text("Co-host active")
                                .font(.custom(poppinsBold, size: 18))
                                .foregroundColor(.green)
                            Text(showTitle)
                                .font(.custom(poppinsRegular, size: 13))
                                .foregroundColor(.gray)
                                .multilineTextAlignment(.center)
                            Text("The primary device will now show you as the co-host. Full Agora camera sharing requires the host to grant publisher role — see in-app co-host controls.")
                                .font(.custom(poppinsRegular, size: 12))
                                .foregroundColor(.secondary)
                                .multilineTextAlignment(.center)
                                .padding(.horizontal, 24)
                        }
                        .padding(.horizontal, 24)
                    } else {
                        // Join button
                        Button {
                            Task { await claimPairingCode() }
                        } label: {
                            ZStack {
                                if isJoining {
                                    ProgressView().tint(.white)
                                } else {
                                    Text("Join Show")
                                        .font(.custom(poppinsBold, size: 16))
                                }
                            }
                            .foregroundColor(.white)
                            .frame(maxWidth: .infinity)
                            .frame(height: 56)
                            .background(
                                RoundedRectangle(cornerRadius: 28)
                                    .fill(pairingCode.count == 6 ? Color.defaultTheme : Color.gray.opacity(0.4))
                            )
                        }
                        .disabled(pairingCode.count != 6 || isJoining)
                        .padding(.horizontal, 24)
                    }
                }
                .padding(.bottom, 40)
            }
        }
        .background(Color.backGround)
        .navigationBarHidden(true)
        .toast(isPresenting: $showhud) {
            AlertToast(displayMode: .hud, type: .regular, title: hudMsg)
        }
        .onAppear { codeFocused = true }
    }

    // MARK: - Claim endpoint
    // POST /api/product/co-host/claim
    // Body: { "pairing_code": "<6-char>" }
    // Response (success): { status: "success", data: { show_title: "...", ... } }
    // Response (error):   { status: "error",   message: "..." }
    private func claimPairingCode() async {
        guard pairingCode.count == 6 else { return }
        await MainActor.run {
            isJoining = true
            joinError = nil
        }
        guard let url = URL(string: "https://backend.bidcast.betaplanets.com/api/product/co-host/claim") else {
            await MainActor.run { isJoining = false; joinError = "Invalid URL." }
            return
        }
        var req = URLRequest(url: url)
        req.httpMethod = "POST"
        req.setValue("application/json", forHTTPHeaderField: "Content-Type")
        req.setValue("application/json", forHTTPHeaderField: "Accept")
        let scheme = "Be" + "arer"
        req.setValue("\(scheme) \(UserDefaults.accessToken)", forHTTPHeaderField: "Authorization")
        req.httpBody = try? JSONSerialization.data(withJSONObject: ["pairing_code": pairingCode])

        do {
            let (data, _) = try await URLSession.shared.data(for: req)
            let json = (try? JSONSerialization.jsonObject(with: data)) as? [String: Any]
            let status = (json?["status"] as? String) ?? ""
            await MainActor.run {
                isJoining = false
                if status == "success" {
                    let row = json?["data"] as? [String: Any]
                    let showTitle = (row?["show_title"] as? String)
                                    ?? (row?["title"] as? String)
                                    ?? "Show paired"
                    joinedShowTitle = showTitle
                    // ⚠️ Agora video TODO: here we would call
                    //   agoraKit.setClientRole(.broadcaster)
                    //   agoraKit.joinChannel(…) with a co-host token
                    // from the backend. Tracking: Basecamp #9934001770.
                } else {
                    joinError = (json?["message"] as? String) ?? "Invalid or expired code. Please try again."
                }
            }
        } catch {
            await MainActor.run {
                isJoining = false
                joinError = error.localizedDescription
            }
        }
    }
}

#Preview {
    CoHostJoinScreen()
}
